//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 03:00:47 PM CEST 
//


package it.makeit.cbi;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CBIGroupHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CBIGroupHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgId" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}Max35Text"/>
 *         &lt;element name="CreDtTm" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}ISODateTime"/>
 *         &lt;element name="NbOfTxs" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}Max15NumericText"/>
 *         &lt;element name="CtrlSum" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIDecimalNumber"/>
 *         &lt;element name="InitgPty" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIPartyIdentification1"/>
 *         &lt;element name="FwdgAgt" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIBranchAndFinancialInstitutionIdentification1" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CBIGroupHeader", propOrder = {
    "msgId",
    "creDtTm",
    "nbOfTxs",
    "ctrlSum",
    "initgPty",
    "fwdgAgt"
})
public class CBIGroupHeader {

    @XmlElement(name = "MsgId", required = true)
    protected int msgId;
    @XmlElement(name = "CreDtTm", required = true)
    protected XMLGregorianCalendar creDtTm;
    @XmlElement(name = "NbOfTxs", required = true)
    protected String nbOfTxs;
    @XmlElement(name = "CtrlSum", required = true)
    protected BigDecimal ctrlSum;
    @XmlElement(name = "InitgPty", required = true)
    protected CBIPartyIdentification1 initgPty;
    @XmlElement(name = "FwdgAgt")
    protected CBIBranchAndFinancialInstitutionIdentification1 fwdgAgt;

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public int getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setMsgId(int msgId) {
       this.msgId = msgId;
    }


    /**
     * Gets the value of the creDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreDtTm() {
        return creDtTm;
    }

    /**
     * Sets the value of the creDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreDtTm(XMLGregorianCalendar value) {
        this.creDtTm = value;
    }

    /**
     * Gets the value of the nbOfTxs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbOfTxs() {
        return nbOfTxs;
    }

    /**
     * Sets the value of the nbOfTxs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbOfTxs(String value) {
        this.nbOfTxs = value;
    }

    /**
     * Gets the value of the ctrlSum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCtrlSum() {
        return ctrlSum;
    }

    /**
     * Sets the value of the ctrlSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCtrlSum(BigDecimal value) {
        this.ctrlSum = value;
    }

    /**
     * Gets the value of the initgPty property.
     * 
     * @return
     *     possible object is
     *     {@link CBIPartyIdentification1 }
     *     
     */
    public CBIPartyIdentification1 getInitgPty() {
        return initgPty;
    }

    /**
     * Sets the value of the initgPty property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIPartyIdentification1 }
     *     
     */
    public void setInitgPty(CBIPartyIdentification1 value) {
        this.initgPty = value;
    }

    /**
     * Gets the value of the fwdgAgt property.
     * 
     * @return
     *     possible object is
     *     {@link CBIBranchAndFinancialInstitutionIdentification1 }
     *     
     */
    public CBIBranchAndFinancialInstitutionIdentification1 getFwdgAgt() {
        return fwdgAgt;
    }

    /**
     * Sets the value of the fwdgAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIBranchAndFinancialInstitutionIdentification1 }
     *     
     */
    public void setFwdgAgt(CBIBranchAndFinancialInstitutionIdentification1 value) {
        this.fwdgAgt = value;
    }

}
