//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 03:00:47 PM CEST 
//


package it.makeit.cbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CBIPaymentRequest.00.04.00 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CBIPaymentRequest.00.04.00">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIGroupHeader"/>
 *         &lt;element name="PmtInf" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIPaymentInstructionInformation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "CBIPaymentRequest")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CBIPaymentRequest.00.04.00", propOrder = {
    "grpHdr",
    "pmtInf"
})
public class CBIPaymentRequest000400 {

    @XmlElement(name = "GrpHdr", required = true)
    protected CBIGroupHeader grpHdr;
    @XmlElement(name = "PmtInf", required = true)
    protected CBIPaymentInstructionInformation pmtInf;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link CBIGroupHeader }
     *     
     */
    public CBIGroupHeader getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIGroupHeader }
     *     
     */
    public void setGrpHdr(CBIGroupHeader value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the pmtInf property.
     * 
     * @return
     *     possible object is
     *     {@link CBIPaymentInstructionInformation }
     *     
     */
    public CBIPaymentInstructionInformation getPmtInf() {
        return pmtInf;
    }

    /**
     * Sets the value of the pmtInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIPaymentInstructionInformation }
     *     
     */
    public void setPmtInf(CBIPaymentInstructionInformation value) {
        this.pmtInf = value;
    }

}
