//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 03:00:47 PM CEST 
//


package it.makeit.cbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CBIParty1Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CBIParty1Choice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="OrgId" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIOrganisationIdentification2"/>
 *           &lt;element name="PrvtId" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIPersonIdentification1"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CBIParty1Choice", propOrder = {
    "orgId",
    "prvtId"
})
public class CBIParty1Choice {

    @XmlElement(name = "OrgId")
    protected CBIOrganisationIdentification2 orgId;
    @XmlElement(name = "PrvtId")
    protected CBIPersonIdentification1 prvtId;

    /**
     * Gets the value of the orgId property.
     * 
     * @return
     *     possible object is
     *     {@link CBIOrganisationIdentification2 }
     *     
     */
    public CBIOrganisationIdentification2 getOrgId() {
        return orgId;
    }

    /**
     * Sets the value of the orgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIOrganisationIdentification2 }
     *     
     */
    public void setOrgId(CBIOrganisationIdentification2 value) {
        this.orgId = value;
    }

    /**
     * Gets the value of the prvtId property.
     * 
     * @return
     *     possible object is
     *     {@link CBIPersonIdentification1 }
     *     
     */
    public CBIPersonIdentification1 getPrvtId() {
        return prvtId;
    }

    /**
     * Sets the value of the prvtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIPersonIdentification1 }
     *     
     */
    public void setPrvtId(CBIPersonIdentification1 value) {
        this.prvtId = value;
    }

}
