//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 03:00:47 PM CEST 
//


package it.makeit.cbi;

import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CBIPaymentInstructionInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CBIPaymentInstructionInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PmtInfId" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}Max35Text"/>
 *         &lt;element name="PmtMtd" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}PaymentMethod3Code"/>
 *         &lt;element name="BtchBookg" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}BatchBookingIndicator" minOccurs="0"/>
 *         &lt;element name="PmtTpInf" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIPaymentTypeInformation1" minOccurs="0"/>
 *         &lt;element name="ReqdExctnDt" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}ISODate"/>
 *         &lt;element name="Dbtr" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIPartyIdentification4"/>
 *         &lt;element name="DbtrAcct" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBICashAccount2"/>
 *         &lt;element name="DbtrAgt" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIBranchAndFinancialInstitutionIdentification2"/>
 *         &lt;element name="UltmtDbtr" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIPartyIdentification2" minOccurs="0"/>
 *         &lt;element name="ChrgBr" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIChargeBearerTypeCode" minOccurs="0"/>
 *         &lt;element name="ChrgsAcct" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBICashAccount1" minOccurs="0"/>
 *         &lt;element name="CdtTrfTxInf" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBICreditTransferTransactionInformation" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CBIPaymentInstructionInformation", propOrder = {
    "pmtInfId",
    "pmtMtd",
    "btchBookg",
    "pmtTpInf",
    "reqdExctnDt",
    "dbtr",
    "dbtrAcct",
    "dbtrAgt",
    "ultmtDbtr",
    "chrgBr",
    "chrgsAcct",
    "cdtTrfTxInf"
})
public class CBIPaymentInstructionInformation {

    @XmlElement(name = "PmtInfId", required = true)
    protected String pmtInfId;
    @XmlElement(name = "PmtMtd", required = true)
    protected PaymentMethod3Code pmtMtd;
    @XmlElement(name = "BtchBookg")
    protected Boolean btchBookg;
    @XmlElement(name = "PmtTpInf")
    protected CBIPaymentTypeInformation1 pmtTpInf;
    @XmlElement(name = "ReqdExctnDt", required = true)
    protected String reqdExctnDt;
    @XmlElement(name = "Dbtr", required = true)
    protected CBIPartyIdentification4 dbtr;
    @XmlElement(name = "DbtrAcct", required = true)
    protected CBICashAccount2 dbtrAcct;
    @XmlElement(name = "DbtrAgt", required = true)
    protected CBIBranchAndFinancialInstitutionIdentification2 dbtrAgt;
    @XmlElement(name = "UltmtDbtr")
    protected CBIPartyIdentification2 ultmtDbtr;
    @XmlElement(name = "ChrgBr")
    protected CBIChargeBearerTypeCode chrgBr;
    @XmlElement(name = "ChrgsAcct")
    protected CBICashAccount1 chrgsAcct;
    @XmlElement(name = "CdtTrfTxInf", required = true)
    protected List<CBICreditTransferTransactionInformation> cdtTrfTxInf;

    public void setCdtTrfTxInf(List<CBICreditTransferTransactionInformation> cdtTrfTxInf) {
		this.cdtTrfTxInf = cdtTrfTxInf;
	}

	/**
     * Gets the value of the pmtInfId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtInfId() {
        return pmtInfId;
    }

    /**
     * Sets the value of the pmtInfId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtInfId(String value) {
        this.pmtInfId = value;
    }

    /**
     * Gets the value of the pmtMtd property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethod3Code }
     *     
     */
    public PaymentMethod3Code getPmtMtd() {
        return pmtMtd;
    }

    /**
     * Sets the value of the pmtMtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethod3Code }
     *     
     */
    public void setPmtMtd(PaymentMethod3Code value) {
        this.pmtMtd = value;
    }

    /**
     * Gets the value of the btchBookg property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBtchBookg() {
        return btchBookg;
    }

    /**
     * Sets the value of the btchBookg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBtchBookg(Boolean value) {
        this.btchBookg = value;
    }

    /**
     * Gets the value of the pmtTpInf property.
     * 
     * @return
     *     possible object is
     *     {@link CBIPaymentTypeInformation1 }
     *     
     */
    public CBIPaymentTypeInformation1 getPmtTpInf() {
        return pmtTpInf;
    }

    /**
     * Sets the value of the pmtTpInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIPaymentTypeInformation1 }
     *     
     */
    public void setPmtTpInf(CBIPaymentTypeInformation1 value) {
        this.pmtTpInf = value;
    }

    /**
     * Gets the value of the reqdExctnDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getReqdExctnDt() {
        return reqdExctnDt;
    }

    /**
     * Sets the value of the reqdExctnDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReqdExctnDt(String value) {
        this.reqdExctnDt = value;
    }

    /**
     * Gets the value of the dbtr property.
     * 
     * @return
     *     possible object is
     *     {@link CBIPartyIdentification4 }
     *     
     */
    public CBIPartyIdentification4 getDbtr() {
        return dbtr;
    }

    /**
     * Sets the value of the dbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIPartyIdentification4 }
     *     
     */
    public void setDbtr(CBIPartyIdentification4 value) {
        this.dbtr = value;
    }

    /**
     * Gets the value of the dbtrAcct property.
     * 
     * @return
     *     possible object is
     *     {@link CBICashAccount2 }
     *     
     */
    public CBICashAccount2 getDbtrAcct() {
        return dbtrAcct;
    }

    /**
     * Sets the value of the dbtrAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBICashAccount2 }
     *     
     */
    public void setDbtrAcct(CBICashAccount2 value) {
        this.dbtrAcct = value;
    }

    /**
     * Gets the value of the dbtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link CBIBranchAndFinancialInstitutionIdentification2 }
     *     
     */
    public CBIBranchAndFinancialInstitutionIdentification2 getDbtrAgt() {
        return dbtrAgt;
    }

    /**
     * Sets the value of the dbtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIBranchAndFinancialInstitutionIdentification2 }
     *     
     */
    public void setDbtrAgt(CBIBranchAndFinancialInstitutionIdentification2 value) {
        this.dbtrAgt = value;
    }

    /**
     * Gets the value of the ultmtDbtr property.
     * 
     * @return
     *     possible object is
     *     {@link CBIPartyIdentification2 }
     *     
     */
    public CBIPartyIdentification2 getUltmtDbtr() {
        return ultmtDbtr;
    }

    /**
     * Sets the value of the ultmtDbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIPartyIdentification2 }
     *     
     */
    public void setUltmtDbtr(CBIPartyIdentification2 value) {
        this.ultmtDbtr = value;
    }

    /**
     * Gets the value of the chrgBr property.
     * 
     * @return
     *     possible object is
     *     {@link CBIChargeBearerTypeCode }
     *     
     */
    public CBIChargeBearerTypeCode getChrgBr() {
        return chrgBr;
    }

    /**
     * Sets the value of the chrgBr property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIChargeBearerTypeCode }
     *     
     */
    public void setChrgBr(CBIChargeBearerTypeCode value) {
        this.chrgBr = value;
    }

    /**
     * Gets the value of the chrgsAcct property.
     * 
     * @return
     *     possible object is
     *     {@link CBICashAccount1 }
     *     
     */
    public CBICashAccount1 getChrgsAcct() {
        return chrgsAcct;
    }

    /**
     * Sets the value of the chrgsAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBICashAccount1 }
     *     
     */
    public void setChrgsAcct(CBICashAccount1 value) {
        this.chrgsAcct = value;
    }

    /**
     * Gets the value of the cdtTrfTxInf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cdtTrfTxInf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCdtTrfTxInf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CBICreditTransferTransactionInformation }
     * 
     * 
     */
    
    
    
    public List<CBICreditTransferTransactionInformation> getCdtTrfTxInf() {
        return this.cdtTrfTxInf;
    }

}
