//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 03:00:47 PM CEST 
//


package it.makeit.cbi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CBIRegulatoryReporting1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CBIRegulatoryReporting1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DbtCdtRptgInd" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIRegulatoryReportingType1Code"/>
 *         &lt;element name="Dtls" type="{urn:CBI:xsd:CBIPaymentRequest.00.04.00}CBIStructuredRegulatoryReporting1" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CBIRegulatoryReporting1", propOrder = {
    "dbtCdtRptgInd",
    "dtls"
})
public class CBIRegulatoryReporting1 {

    @XmlElement(name = "DbtCdtRptgInd", required = true)
    protected CBIRegulatoryReportingType1Code dbtCdtRptgInd;
    @XmlElement(name = "Dtls")
    protected CBIStructuredRegulatoryReporting1 dtls;

    /**
     * Gets the value of the dbtCdtRptgInd property.
     * 
     * @return
     *     possible object is
     *     {@link CBIRegulatoryReportingType1Code }
     *     
     */
    public CBIRegulatoryReportingType1Code getDbtCdtRptgInd() {
        return dbtCdtRptgInd;
    }

    /**
     * Sets the value of the dbtCdtRptgInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIRegulatoryReportingType1Code }
     *     
     */
    public void setDbtCdtRptgInd(CBIRegulatoryReportingType1Code value) {
        this.dbtCdtRptgInd = value;
    }

    /**
     * Gets the value of the dtls property.
     * 
     * @return
     *     possible object is
     *     {@link CBIStructuredRegulatoryReporting1 }
     *     
     */
    public CBIStructuredRegulatoryReporting1 getDtls() {
        return dtls;
    }

    /**
     * Sets the value of the dtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBIStructuredRegulatoryReporting1 }
     *     
     */
    public void setDtls(CBIStructuredRegulatoryReporting1 value) {
        this.dtls = value;
    }

}
