//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 03:00:47 PM CEST 
//


package it.makeit.cbi;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.makeit.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CBIPaymentRequest_QNAME = new QName("urn:CBI:xsd:CBIPaymentRequest.00.04.00", "CBIPaymentRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.makeit.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CBIPaymentRequest000400 }
     * 
     */
    public CBIPaymentRequest000400 createCBIPaymentRequest000400() {
        return new CBIPaymentRequest000400();
    }

    /**
     * Create an instance of {@link CBIBranchAndFinancialInstitutionIdentification1 }
     * 
     */
    public CBIBranchAndFinancialInstitutionIdentification1 createCBIBranchAndFinancialInstitutionIdentification1() {
        return new CBIBranchAndFinancialInstitutionIdentification1();
    }

    /**
     * Create an instance of {@link CBIBranchAndFinancialInstitutionIdentification3 }
     * 
     */
    public CBIBranchAndFinancialInstitutionIdentification3 createCBIBranchAndFinancialInstitutionIdentification3() {
        return new CBIBranchAndFinancialInstitutionIdentification3();
    }

    /**
     * Create an instance of {@link CBIBranchAndFinancialInstitutionIdentification2 }
     * 
     */
    public CBIBranchAndFinancialInstitutionIdentification2 createCBIBranchAndFinancialInstitutionIdentification2() {
        return new CBIBranchAndFinancialInstitutionIdentification2();
    }

    /**
     * Create an instance of {@link RemittanceAmount1 }
     * 
     */
    public RemittanceAmount1 createRemittanceAmount1() {
        return new RemittanceAmount1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link CBIAccountIdentification1 }
     * 
     */
    public CBIAccountIdentification1 createCBIAccountIdentification1() {
        return new CBIAccountIdentification1();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4 }
     * 
     */
    public OrganisationIdentification4 createOrganisationIdentification4() {
        return new OrganisationIdentification4();
    }

    /**
     * Create an instance of {@link CBIServiceLevel2 }
     * 
     */
    public CBIServiceLevel2 createCBIServiceLevel2() {
        return new CBIServiceLevel2();
    }

    /**
     * Create an instance of {@link CBIServiceLevel1 }
     * 
     */
    public CBIServiceLevel1 createCBIServiceLevel1() {
        return new CBIServiceLevel1();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link CBIPaymentInstructionInformation }
     * 
     */
    public CBIPaymentInstructionInformation createCBIPaymentInstructionInformation() {
        return new CBIPaymentInstructionInformation();
    }

    /**
     * Create an instance of {@link CBIFinancialInstitutionIdentification2 }
     * 
     */
    public CBIFinancialInstitutionIdentification2 createCBIFinancialInstitutionIdentification2() {
        return new CBIFinancialInstitutionIdentification2();
    }

    /**
     * Create an instance of {@link CBIFinancialInstitutionIdentification1 }
     * 
     */
    public CBIFinancialInstitutionIdentification1 createCBIFinancialInstitutionIdentification1() {
        return new CBIFinancialInstitutionIdentification1();
    }

    /**
     * Create an instance of {@link CBIFinancialInstitutionIdentification3 }
     * 
     */
    public CBIFinancialInstitutionIdentification3 createCBIFinancialInstitutionIdentification3() {
        return new CBIFinancialInstitutionIdentification3();
    }

    /**
     * Create an instance of {@link CBICheque1 }
     * 
     */
    public CBICheque1 createCBICheque1() {
        return new CBICheque1();
    }

    /**
     * Create an instance of {@link CBIRemittanceLocation1 }
     * 
     */
    public CBIRemittanceLocation1 createCBIRemittanceLocation1() {
        return new CBIRemittanceLocation1();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link CBIParty1Choice }
     * 
     */
    public CBIParty1Choice createCBIParty1Choice() {
        return new CBIParty1Choice();
    }

    /**
     * Create an instance of {@link GenericIdentification3 }
     * 
     */
    public GenericIdentification3 createGenericIdentification3() {
        return new GenericIdentification3();
    }

    /**
     * Create an instance of {@link CBICashAccount1 }
     * 
     */
    public CBICashAccount1 createCBICashAccount1() {
        return new CBICashAccount1();
    }

    /**
     * Create an instance of {@link CBICashAccount2 }
     * 
     */
    public CBICashAccount2 createCBICashAccount2() {
        return new CBICashAccount2();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link ReferredDocumentType1Choice }
     * 
     */
    public ReferredDocumentType1Choice createReferredDocumentType1Choice() {
        return new ReferredDocumentType1Choice();
    }

    /**
     * Create an instance of {@link CBIOrganisationIdentification1 }
     * 
     */
    public CBIOrganisationIdentification1 createCBIOrganisationIdentification1() {
        return new CBIOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     * 
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     * 
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation7 }
     * 
     */
    public StructuredRemittanceInformation7 createStructuredRemittanceInformation7() {
        return new StructuredRemittanceInformation7();
    }

    /**
     * Create an instance of {@link CBIRegulatoryReporting1 }
     * 
     */
    public CBIRegulatoryReporting1 createCBIRegulatoryReporting1() {
        return new CBIRegulatoryReporting1();
    }

    /**
     * Create an instance of {@link PartyIdentification32 }
     * 
     */
    public PartyIdentification32 createPartyIdentification32() {
        return new PartyIdentification32();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation3 }
     * 
     */
    public ReferredDocumentInformation3 createReferredDocumentInformation3() {
        return new ReferredDocumentInformation3();
    }

    /**
     * Create an instance of {@link CBIGroupHeader }
     * 
     */
    public CBIGroupHeader createCBIGroupHeader() {
        return new CBIGroupHeader();
    }

    /**
     * Create an instance of {@link Party6Choice }
     * 
     */
    public Party6Choice createParty6Choice() {
        return new Party6Choice();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link CBIAmountType1 }
     * 
     */
    public CBIAmountType1 createCBIAmountType1() {
        return new CBIAmountType1();
    }

    /**
     * Create an instance of {@link CBILocalInstrument1 }
     * 
     */
    public CBILocalInstrument1 createCBILocalInstrument1() {
        return new CBILocalInstrument1();
    }

    /**
     * Create an instance of {@link CBIStructuredRegulatoryReporting1 }
     * 
     */
    public CBIStructuredRegulatoryReporting1 createCBIStructuredRegulatoryReporting1() {
        return new CBIStructuredRegulatoryReporting1();
    }

    /**
     * Create an instance of {@link CBIOrganisationIdentification4 }
     * 
     */
    public CBIOrganisationIdentification4 createCBIOrganisationIdentification4() {
        return new CBIOrganisationIdentification4();
    }

    /**
     * Create an instance of {@link CBIOrganisationIdentification3 }
     * 
     */
    public CBIOrganisationIdentification3 createCBIOrganisationIdentification3() {
        return new CBIOrganisationIdentification3();
    }

    /**
     * Create an instance of {@link CBICreditTransferTransactionInformation }
     * 
     */
    public CBICreditTransferTransactionInformation createCBICreditTransferTransactionInformation() {
        return new CBICreditTransferTransactionInformation();
    }

    /**
     * Create an instance of {@link CBIOrganisationIdentification2 }
     * 
     */
    public CBIOrganisationIdentification2 createCBIOrganisationIdentification2() {
        return new CBIOrganisationIdentification2();
    }

    /**
     * Create an instance of {@link PaymentIdentification1 }
     * 
     */
    public PaymentIdentification1 createPaymentIdentification1() {
        return new PaymentIdentification1();
    }

    /**
     * Create an instance of {@link RemittanceInformation5 }
     * 
     */
    public RemittanceInformation5 createRemittanceInformation5() {
        return new RemittanceInformation5();
    }

    /**
     * Create an instance of {@link ContactDetails2 }
     * 
     */
    public ContactDetails2 createContactDetails2() {
        return new ContactDetails2();
    }

    /**
     * Create an instance of {@link ReferredDocumentType2 }
     * 
     */
    public ReferredDocumentType2 createReferredDocumentType2() {
        return new ReferredDocumentType2();
    }

    /**
     * Create an instance of {@link CBIPaymentTypeInformation1 }
     * 
     */
    public CBIPaymentTypeInformation1 createCBIPaymentTypeInformation1() {
        return new CBIPaymentTypeInformation1();
    }

    /**
     * Create an instance of {@link Purpose1Choice }
     * 
     */
    public Purpose1Choice createPurpose1Choice() {
        return new Purpose1Choice();
    }

    /**
     * Create an instance of {@link CBIPaymentTypeInformation2 }
     * 
     */
    public CBIPaymentTypeInformation2 createCBIPaymentTypeInformation2() {
        return new CBIPaymentTypeInformation2();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link CBIPersonIdentification1 }
     * 
     */
    public CBIPersonIdentification1 createCBIPersonIdentification1() {
        return new CBIPersonIdentification1();
    }

    /**
     * Create an instance of {@link CBIClearingSystemMemberIdentification1 }
     * 
     */
    public CBIClearingSystemMemberIdentification1 createCBIClearingSystemMemberIdentification1() {
        return new CBIClearingSystemMemberIdentification1();
    }

    /**
     * Create an instance of {@link CBIPartyIdentification2 }
     * 
     */
    public CBIPartyIdentification2 createCBIPartyIdentification2() {
        return new CBIPartyIdentification2();
    }

    /**
     * Create an instance of {@link CBIPartyIdentification3 }
     * 
     */
    public CBIPartyIdentification3 createCBIPartyIdentification3() {
        return new CBIPartyIdentification3();
    }

    /**
     * Create an instance of {@link CBIPartyIdentification4 }
     * 
     */
    public CBIPartyIdentification4 createCBIPartyIdentification4() {
        return new CBIPartyIdentification4();
    }

    /**
     * Create an instance of {@link CBIPartyIdentification5 }
     * 
     */
    public CBIPartyIdentification5 createCBIPartyIdentification5() {
        return new CBIPartyIdentification5();
    }

    /**
     * Create an instance of {@link CBIIdType1 }
     * 
     */
    public CBIIdType1 createCBIIdType1() {
        return new CBIIdType1();
    }

    /**
     * Create an instance of {@link CBIIdType2 }
     * 
     */
    public CBIIdType2 createCBIIdType2() {
        return new CBIIdType2();
    }

    /**
     * Create an instance of {@link CBIPostalAddress6 }
     * 
     */
    public CBIPostalAddress6 createCBIPostalAddress6() {
        return new CBIPostalAddress6();
    }

    /**
     * Create an instance of {@link CBIGenericIdentification2 }
     * 
     */
    public CBIGenericIdentification2 createCBIGenericIdentification2() {
        return new CBIGenericIdentification2();
    }

    /**
     * Create an instance of {@link CBIIdType3 }
     * 
     */
    public CBIIdType3 createCBIIdType3() {
        return new CBIIdType3();
    }

    /**
     * Create an instance of {@link CBIPartyIdentification1 }
     * 
     */
    public CBIPartyIdentification1 createCBIPartyIdentification1() {
        return new CBIPartyIdentification1();
    }

    /**
     * Create an instance of {@link CBIGenericIdentification1 }
     * 
     */
    public CBIGenericIdentification1 createCBIGenericIdentification1() {
        return new CBIGenericIdentification1();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CBIPaymentRequest000400 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:CBI:xsd:CBIPaymentRequest.00.04.00", name = "CBIPaymentRequest")
    public JAXBElement<CBIPaymentRequest000400> createCBIPaymentRequest(CBIPaymentRequest000400 value) {
        return new JAXBElement<CBIPaymentRequest000400>(_CBIPaymentRequest_QNAME, CBIPaymentRequest000400 .class, null, value);
    }

}
