//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 03:00:47 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:CBI:xsd:CBIPaymentRequest.00.04.00", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.makeit.cbi;
